### PR TITLE
Use `serde_bytes`

### LINKED ISSUE #66: PublicKey incompatible with serde_json
During testing I encountered an error when trying to deserialize a `PublicKey` from a `serde_json::Value` 

Error:
```
thread 'main' panicked at 'unable to deserialize PublicKey: Error("invalid type: sequence, expected A Ristretto Schnorr public key represented as a 32-byte Ristretto compressed point", line: 0, column: 0)', src/main.rs:11:40
```

example code can be found [here](https://github.com/becominginsane/schnorrkel-serde).

I think this can be fixed in multiple ways, either by implementing `visit_seq` or by making use of [serde_bytes](https://docs.rs/serde_bytes/0.11.5/serde_bytes/) (even tho it will probably mean that it'll be necessary to wrap with `Bytes` during serialization / deserialization manually instead of using the attributes offered)

### PR DESCRIPTION
**Pull request by becominginsane**
This PR addresses the issue outlined in #66.

2 new dependencies were added: `serde_bytes` to actually use when serializing and deserializing, and `cfg_if`, so deserialization can use `Bytes` when in no `alloc` context and `BytesBuf` otherwise, since the latter allows to deserialize from more data types where the size is not known or it is not borrowable, such as sequences.

`serde` has also been renamed in the manifest as `serde_crate`, similar to `curve25519-dalek`'s manifest, to allow bundling `serde_bytes` and `serde` in a single feature flag.

Tests were added to check compatibility with `serde_json`

Closes #66

### CODE REVIEW

File: src/serdey.rs [hunk 1]
```diff
@@ -19,31 +19,27 @@
...
-
-            fn visit_bytes<E>(self, bytes: &[u8]) -> Result<$t, E> where E: ::serde::de::Error {
-                Self::Value::from_bytes(bytes).map_err(crate::errors::serde_error_from_signature_error)
+impl<'d> ::serde_crate::Deserialize<'d> for $t {
+    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: ::serde_crate::Deserializer<'d> {
+        cfg_if::cfg_if!{
+            if #[cfg(any(feature = "alloc", feature = "std"))] {
+                let bytes = <::serde_bytes::ByteBuf>::deserialize(deserializer)?;
+            } else {
+                let bytes = <&::serde_bytes::Bytes>::deserialize(deserializer)?;
```
Comment (burdges) [inline src/serdey.rs:37]: oh cute, what's going on here?

**Comment by burdges** [comment]
Appears we give up the ability to work without serde_bytes, but this should be no sacrifice because its designed to handle all the corner cases?

File: src/serdey.rs (hunk 1 above)
Comment (becominginsane) [reply src/serdey.rs:37]: if we are using the `std` or the `alloc` feature during deserialization we should switch to `ByteBuf` since it [handles more cases](https://github.com/serde-rs/bytes/blob/master/src/bytebuf.rs#L196-L244):

- `visit_seq`
- `visit_byte_buf`
- `visit_string`
- `visit_bytes`
- `visit_str`

`Bytes` [handles](https://github.com/serde-rs/bytes/blob/master/src/bytes.rs#L166-L186):
- `visit_borrowed_bytes`
- `visit_borrowed_str`

But after poking around `serde_bytes` a bit I noticed `Cow<'_, [u8]>` is supported to deserialize into, which could slightly be more efficient

**Comment by becominginsane** [comment]
Yeah `serde_bytes` handles more cases than the previous implementation, so we are good with using it always.

We need the feature because otherwise to properly enable `serde` support we need to specify 2 features, `serde` and `serde_bytes`, which I don't think is ideal, and would also break the current documentation.

I don't see the 3 features you mention? You mean `serde`, `serde_crate` and `serde_bytes`, `cfg_if`? Well the user are not supposed to enable `serde_crate`, `serde_bytes` or `cfg_if` manually, but as far as I know this is the only way to group up optional dependencies together.

I use `cfg_if` to provide different deserialization based on the enabled features, since otherwise we'd drop support for no `alloc`

**Comment by burdges** [comment]
It's ready for merge?

**Comment by becominginsane** [comment]
I'd say so, I ran `cargo test` with different feature sets and it's working :)

Let me know if you have any other concern to address before merging

**Comment by burdges** [comment]
LGTM
